# Generated by Django 3.2.4 on 2021-07-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=35)),
                ('board_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InsideBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.IntegerField()),
                ('SubTitle', models.CharField(max_length=35)),
                ('CardTitle', models.CharField(max_length=35)),
                ('CardBody', models.TextField(max_length=500)),
            ],
        ),
    ]
