# Generated by Django 3.2.5 on 2021-08-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=35)),
                ('slug', models.SlugField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='InsideBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.IntegerField()),
                ('title_id', models.IntegerField()),
                ('SubTitle', models.CharField(max_length=35)),
                ('CardTitle', models.CharField(max_length=35)),
                ('CardBody', models.TextField(max_length=500)),
            ],
        ),
    ]
