# Generated by Django 3.2.4 on 2021-08-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='id',
        ),
        migrations.AlterField(
            model_name='board',
            name='board_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
