# Generated by Django 3.2.4 on 2021-08-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210804_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='insideboard',
            name='title_id',
            field=models.IntegerField(default=None),
        ),
    ]
