# Generated by Django 3.2.4 on 2021-08-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210806_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=35)),
                ('slug', models.SlugField(default=None)),
                ('title_id', models.IntegerField()),
                ('SubTitle', models.CharField(max_length=35)),
                ('CardTitle', models.CharField(max_length=35)),
                ('CardBody', models.TextField(max_length=500)),
            ],
        ),
    ]
