# Generated by Django 3.2.4 on 2021-08-06 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='project',
        ),
        migrations.AlterField(
            model_name='insideboard',
            name='board_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='board.board'),
        ),
    ]
