# Generated by Django 3.2.4 on 2021-08-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_board_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='user',
        ),
    ]
